### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by dishapatel010** [TheDarkW3b/instagram#1]
![Untitled](https://user-images.githubusercontent.com/71930916/98463170-602e4200-21df-11eb-97c5-f1885739f0e1.png)

**Comment by RomanGoddess** [comment]
Same error

**Comment by TheDarkW3b** [comment]
Ahh weird, it's the old code I am not working on it since a day I finished this 🥺

May be their are some changed in the API

**Comment by dishapatel010** [comment]
> Ahh weird, it's the old code I am not working on it since a day I finished this 
> 
> May be their are some changed in the API

try to make UPDARGEs coz its a one perfect open source code

**Comment by Andrio-Codes** [comment]
> ![Untitled](https://user-images.githubusercontent.com/71930916/98463170-602e4200-21df-11eb-97c5-f1885739f0e1.png)

same error

**Comment by Andrio-Codes** [comment]
> Ahh weird, it's the old code I am not working on it since a day I finished this pleading_face
> 
> May be their are some changed in the API

hello sir. i have made the changes according to the new api and now the bot works. please merge my pull request.

**Comment by TheDarkW3b** [comment]
> > Ahh weird, it's the old code I am not working on it since a day I finished this
> > May be their are some changed in the API
> 
> try to make UPDARGEs coz its a one perfect open source code

Haha thanks for the compliment, i have considered this code as a pretty ugly one

**Comment by TheDarkW3b** [comment]
> > Ahh weird, it's the old code I am not working on it since a day I finished this pleading_face
> > May be their are some changed in the API
> 
> hello sir. i have made the changes according to the new api and now the bot works. please merge my pull request.

Oh Thanks, since he fixed it i am marking this as resolved
